USE ALURA_CASH;

SELECT *
FROM ID TB1
LEFT JOIN DADOS_MUTUARIOS TB2 ON TB1.PERSON_ID = TB2.PERSON_ID
LEFT JOIN EMPRESTIMOS TB3 ON TB1.LOAN_ID = TB3.LOAN_ID
LEFT JOIN HISTORICOS_BANCO TB4 ON TB1.CB_ID = TB4.CB_ID;